apiKeyRegistration/config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy', as: :logout
  
  get 'revoke_client' => 'clients#revoke', as: :revoke_client
  get 'reactivate_client' => 'clients#reactivate', as: :reactivate_client
  
  resources :clients, only: [:index, :create, :new, :destroy]
  resources :users, only: [:create, :new]
  resources :admins, only: [:index]
end

apiKeyRegistration/app/models/client.rb
class Client < ActiveRecord::Base
    validates :name, presence: true, length: { maximum: 50 }
    validates :description, length: { maximum: 250 }
    belongs_to :user
end

apiKeyRegistration/app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    validates :username, presence: true, uniqueness: true, length: { in: 3..25 }
    validates :password, length: { minimum: 6 }
    has_many :clients
end

apiKeyRegistration/app/controllers/admins_controller.rb
class AdminsController < ApplicationController
    
    before_action :require_login
    before_action :check_admin_rights
    
    def index
        @clients = Client.all
    end
end

apiKeyRegistration/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :no_cache
  
  private
  # makes sure that current_user is available from views  
  helper_method :current_user
  
  def current_user
    @current_user ||= User.find(session[:userid]) if session[:userid]
  end
  
  def require_login
    if current_user.nil? then
      flash[:danger] = 'Du måste logga in för att se sidan du efterfrågade.'
      redirect_to root_path
    end
  end
  
  def check_admin_rights
    unless current_user.admin?
      flash[:danger] = 'Du har inte rättigheter att visa sidan du efterfrågade.'
      redirect_to clients_path
    end
  end
  
  def no_cache
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end
  
end

apiKeyRegistration/app/controllers/clients_controller.rb
class ClientsController < ApplicationController
    
    before_action :require_login
    before_action :fetch_client, only: [:destroy, :revoke, :reactivate]
    
    def index
        @user = User.find(session[:userid])
    end
    
    def new
        @client = Client.new
    end
    
    def create
        @client = Client.new(client_params)
        @client.key = DateTime.now.strftime('%s') + SecureRandom.hex(20)
        @client.user_id = session[:userid]
        
        if @client.save
           flash[:success] = 'Applikationen sparades.'
           redirect_to clients_path
        else
            flash[:danger] = 'Applikationen kunde inte sparas.'
            render :action => 'new'
        end
    end
    
    def destroy
        @client.destroy
        flash[:success] = 'Applikationen raderades.'
        if current_user.admin?
            redirect_to admins_path
        else
            redirect_to clients_path
        end
    end
    
    def revoke
        @client.active = false
        @client.save
        flash[:success] = 'Applikationen har inaktiverats.'
        redirect_to admins_path
    end
    
    def reactivate
        @client.active = true
        @client.save
        flash[:success] = 'Applikationen har återaktiverats.'
        redirect_to admins_path
    end
    
    private
    
    def client_params
        params.require(:client).permit(:name, :description, :url)
    end
    
    private
    
    def fetch_client
      @client = Client.find(params[:id])
    end
end

apiKeyRegistration/app/controllers/session_controller.rb
class SessionController < ApplicationController
    
    def index
    end
    
    def login
        u = User.find_by_username(params[:username])
        if u && u.authenticate(params[:password])
            session[:userid] = u.id
            redirect_to apikey_path
        else
            flash[:notice] = 'Fel vid inloggning.'
            redirect_to root_path
        end
    end
    
    def logout
        session[:userid] = nil
        redirect_to root_path, :notice => 'Du har loggat ut'
    end
end

apiKeyRegistration/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
    end
    
    def create
        u = User.find_by_username(params[:username])
        if u && u.authenticate(params[:password])
            session[:userid] = u.id
            if u.admin
                redirect_to admins_path
            else
                redirect_to clients_path
            end
        else
            flash[:danger] = 'Fel vid inloggning.'
            redirect_to root_path
        end
    end
    
    def destroy
        session[:userid] = nil
        flash[:success] = 'Du har loggat ut.'
        redirect_to root_path
    end
end

apiKeyRegistration/app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        
        if @user.save
           session[:userid] = @user.id 
           flash[:success] = 'Du är nu en registrerad användare.'
           redirect_to clients_path
        else
            if User.find_by username: @user.username
                flash[:danger] = 'Användarnamnet är upptaget. Prova med något annat.'
                render :action => 'new' and return
            end
            flash[:danger] = 'Något gick fel vid registreringen.'
            render 'new'
        end
    end
    
    private
    def user_params
        params.require(:user).permit(:username, :password, :password_confirmation)
    end

end

apiKeyRegistration/app/helpers/admins_helper.rb
module AdminsHelper
end

apiKeyRegistration/app/helpers/application_helper.rb
module ApplicationHelper
end

apiKeyRegistration/app/helpers/clients_helper.rb
module ClientsHelper
end

apiKeyRegistration/app/helpers/sessions_helper.rb
module SessionsHelper
end

apiKeyRegistration/app/helpers/users_helper.rb
module UsersHelper
end

apiKeyRegistration/app/views/admins/index.html.erb
<h1>Applikationer</h1>
<div>
    <ul id="user-clients">
        <% @clients.each do |client| %>
            <li>
                <h2><%= client.name %></h2>
                <p><strong>Användare:</strong> <%= client.user.username %></p>
                <p><strong>API-nyckel:</strong> <%= client.key %></p>
                
                <% if client.active %>
                    <p class="active"><strong>Status: </strong>Aktiv</p>
                <% else %>
                    <p class="inactive"><strong>Status: </strong>Inaktiverad av admin</p>
                <% end %>
                
                <p><strong>Url:</strong> <%= client.url %></p>
                <p><strong>Beskrivning:</strong> <%= client.description %></p>
                
                <% if client.active %>
                    <%= link_to 'Inaktivera', revoke_client_path(id: client.id) %>
                <% else %>
                    <%= link_to 'Återaktivera', reactivate_client_path(id: client.id) %>
                <% end %>
                <br/>
                <%= link_to "Ta bort (går inte att ångra)", client, method: :delete %>
            </li>
        <% end %>
    </ul>
</div>

apiKeyRegistration/app/views/admins/show.html.erb
<h1>Applikationer</h1>
<div>
    <ul id="user-clients">
        <% @clients.each do |client| %>
            <li>
                <h2><%= client.name %></h2>
                <p><strong>Användare:</strong> <%= client.user.username %></p>
                <p><strong>API-nyckel:</strong> <%= client.key %></p>
                
                <% if client.active %>
                    <p class="active"><strong>Status: </strong>Aktiv</p>
                <% else %>
                    <p class="inactive"><strong>Status: </strong>Inaktiverad av admin</p>
                <% end %>
                
                <p><strong>Url:</strong> <%= client.url %></p>
                <p><strong>Beskrivning:</strong> <%= client.description %></p>
                
                <% if client.active %>
                    <%= link_to 'Inaktivera', revoke_client_path(id: client.id) %>
                <% else %>
                    <%= link_to 'Återaktivera', reactivate_client_path(id: client.id) %>
                <% end %>
                <br/>
                <%= link_to 'Radera (går inte att ångra)', delete_client_path(id: client.id), {class: 'red'} %>
            </li>
        <% end %>
    </ul>
</div>

apiKeyRegistration/app/views/clients/index.html.erb
<h1>Applikationer</h1>
<div>
<%= link_to 'Lägg till applikation', new_client_path, :id => 'add-client' %>
<ul id="user-clients">
    <% @user.clients.each do |client| %>
        <li>
            <h2><%= client.name %></h2>
            <p><strong>API-nyckel:</strong> <%= client.key %></p>
            
            <% if client.active %>
                <p class="active"><strong>Status: </strong>Aktiv</p>
            <% else %>
                <p class="inactive"><strong>Status: </strong>Inaktiverad av admin</p>
            <% end %>
            
            <p><strong>Url:</strong> <%= client.url %></p>
            <p><strong>Beskrivning:</strong> <%= client.description %></p>
            <%= link_to "Ta bort (går inte att ångra)", client, method: :delete %>
        </li>
    <% end %>
</ul>
</div>

apiKeyRegistration/app/views/clients/new.html.erb
<div id="register-client">
    <h1>Lägg till applikation</h1>
    <fieldset>
        <%= form_for @client do |c| %>
            <%= c.label 'Namn (max 50 tecken)', :for => 'client_name' %>
            <%= c.text_field :name %>
            <%= c.label 'Beskrivning (max 250 tecken)', :for => 'client_description' %>
            <%= c.text_area :description %>
            <%= c.label :url %>
            <%= c.url_field :url %>
            <%= c.submit 'Skapa', id: "submit" %>
        <% end %>
    </fieldset>
    <%= link_to 'Tillbaka till min sida', clients_path %>
</div>

apiKeyRegistration/app/views/clients/show.html.erb
<h1>Applikationer</h1>
<div>
<%= link_to 'Lägg till applikation', new_client_path, :id => 'add-client' %>
<ul id="user-clients">
    <% @user.clients.each do |client| %>
        <li>
            <h2><%= client.name %></h2>
            <p><strong>API-nyckel:</strong> <%= client.key %></p>
            
            <% if client.active %>
                <p class="active"><strong>Status: </strong>Aktiv</p>
            <% else %>
                <p class="inactive"><strong>Status: </strong>Inaktiverad av admin</p>
            <% end %>
            
            <p><strong>Url:</strong> <%= client.url %></p>
            <p><strong>Beskrivning:</strong> <%= client.description %></p>
            <%= link_to 'Ta bort (går inte att ångra)', delete_client_path(id: client.id), {class: 'red'} %>
        </li>
    <% end %>
</ul>
</div>

apiKeyRegistration/app/views/layouts/_footer.html.erb
<div id="footer" class="container">
    <p>Applikation skapad av Lisa Westlund, som en uppgift i kursen Webbramverk vid Linnéuniversitetet</p>
</div>

apiKeyRegistration/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApiKeyRegistration</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> container">
        <p><%= value %></p>
    </div>
  <% end %>
  
  <div class="container">
    <% if !@current_user.nil? %>
      <div id="user-information">
        <p>Inloggad som: <%= @current_user.username %></p>
        <%= link_to 'Logga ut', logout_path, method: :delete, data: {no_turbolink: true} %>
      </div>
    <% end %>
    <%= yield %>
  </div>
  
  <%= render 'layouts/footer' %>

</body>
</html>

apiKeyRegistration/app/views/session/login.html.erb
<div id="login">
    <h2>Logga in</h2>
    <fieldset>
        <%= form_tag(login_path, method: 'post') do %>
            <p><%= label_tag(:username, 'Användarnamn') %></p>
            <p><%= text_field_tag(:username) %></p>
            <p><%= label_tag(:password, 'Lösenord') %></p>
            <p><%= password_field_tag(:password) %></p>
            <p><%= submit_tag('Logga in') %></p>
        <% end %>
    </fieldset>
    
    <%= link_to 'Registrera ny användare', new_user_path %>
    
</div>

apiKeyRegistration/app/views/users/new.html.erb
<div id="register" class="col-md-4">
    <h1>Registrera</h1>
    <fieldset>
        <%= form_for @user do |f| %>
            <%= f.label 'Användarnamn (3-25 tecken)', :for => 'user_username' %>
            <%= f.text_field :username %>
            <%= f.label 'Lösenord (minst 6 tecken)', :for => 'user_password' %>
            <%= f.password_field :password %>
            <%= f.label 'Ange lösenordet igen', :for => 'user_password_confirmation' %>
            <%= f.password_field :password_confirmation %>
            <%= f.submit 'Registrera', :id => "submit" %>
        <% end %>
    </fieldset>
    <%= link_to 'Tillbaka till startsidan', root_path %>
</div>